### ISSUE TITLE
WIndows compatibility?

### ISSUE THREAD

**Issue by niansa** [jbaldwin/libcoro#102]
Are the non-networking parts compatible with windows?

**Comment by jbaldwin** [comment]
I haven't tried and I don't have any plans on supporting windows.  You're welcome to give it a go though.

**Comment by niansa** [comment]
could you add some cmake option so to not compile networking stuff?

**Comment by niansa** [comment]
(a dependency-free build in a sense)

**Comment by niansa** [comment]
https://gitlab.com/niansa/libcrosscoro
Like this fork I make, but as a cmake option

**Comment by jbaldwin** [comment]
probably would be a good idea to extract the io_scheduler poll functionality into a pimpl style pattern or something that could be instantiated per platform?  That seems like an ideal architecture so more platforms could theoretically be implemented

**Comment by niansa** [comment]
Yeah. I agree
