### ISSUE TITLE
Misunderstanding of atomic::load

### ISSUE THREAD

**Issue by Ankkatalo** [jbaldwin/libcoro#104]
In the function
`auto event::awaiter::await_suspend(std::coroutine_handle<> awaiting_coroutine) noexcept -> bool`

I have found:

    // This value will update if other threads write to it via acquire.
    void* old_value = m_event.m_state.load(std::memory_order::acquire);

and then a loop.

This is plain wrong. The value will not update after the load. And the atomic::load must go into the loop.
In the loop you must:
- read the value
- decide what to do depending on the value
- attempt change the value
until you succeed. But if you never read the old value again after the exit condition has failed you have an endless loop here. 

The problem might exist in other parts of the code as well.

**Comment by jbaldwin-vizio** [comment]
I think the comment "via acquire" is incorrect, and should say "via std::memory_order::release" instead for the memory model to be correct, but if you look further in this function there is a compare and exchange within the loop:

```
} while (!m_event.m_state.compare_exchange_weak(
        old_value, this, std::memory_order::release, std::memory_order::acquire));
```

This releases the memory if the compare and exchange is successful thus updating other threads, _but_ if it isn't successful it creates another acquire memory barrier reloading this variable that you think isn't being reloaded.

If you are unconvinced I suggest reading up on memory models and also look at Lewis Bakers cppcoro event implementation for this exact function, you'll find its basically identical (this is where I learned how this works myself).

**Comment by jbaldwin** [comment]
I think the comment "via acquire" is incorrect, and should say "via std::memory_order::release" instead for the memory model to be correct, but if you look further in this function there is a compare and exchange within the loop:

```
} while (!m_event.m_state.compare_exchange_weak(
        old_value, this, std::memory_order::release, std::memory_order::acquire));
```

This releases the memory if the compare and exchange is successful thus updating other threads, but if it isn't successful it creates another acquire memory barrier reloading this variable that you think isn't being reloaded.

If you are unconvinced I suggest reading up on memory models and also look at Lewis Bakers cppcoro event implementation for this exact function, you'll find its basically identical (this is where I learned how this works myself).

**Comment by Ankkatalo** [comment]
I was plain wrong. I stared at the code for a long while and decided that it make no sense.
The detail I missed is that the first argument to compare_exchange_weak is by reference and old_value is changed by compare_exchange_weak itself if the exchange fails. So the read is in there. 

My apologies, please close this.

**Comment by jbaldwin** [comment]
No problem!  Glad it makes sense now.
