### ISSUE TITLE
Warning about missing co_return

### ISSUE THREAD

**Issue by Ankkatalo** [jbaldwin/libcoro#105]
Visual Studio complains about the function make_sync_wait_task in sync_wait.hpp. It'll paste it here:

static auto make_sync_wait_task(awaitable_type&& a) -> sync_wait_task<return_type>
{
    if constexpr (std::is_void_v<return_type>)
    {
        co_await std::forward<awaitable_type>(a);
        co_return;
    }
    else
    {
        co_yield co_await std::forward<awaitable_type>(a);
    }
}

The warning is:
1>C:\dev\UADR3\SourcesCPP\Libraries\coro\inc\coro\sync_wait.hpp(208,1): warning C4033: 'coro::detail::make_sync_wait_task' must return a value
1>C:\dev\UADR3\SourcesCPP\Libraries\coro\inc\coro\sync_wait.hpp(208,1): message : Flowing off the end of a coroutine results in undefined behavior when promise type 'coro::detail::sync_wait_task_promise<return_type>' does not declare 'return_void'

My understanding of coroutines is for too low to fix this. any ideas?

**Comment by jbaldwin** [comment]
I'm still not planning on any windows support, but if you want to open a PR with github actions to test building against it I'd be happy to include it into the project.
