### ISSUE TITLE
how do I "call and forget"?

### ISSUE THREAD

**Issue by Ankkatalo** [jbaldwin/libcoro#106]
Hello.

I have a normal C++ function here, and from it I'd like to call a coroutine. The coroutine returns a task<void>. 
Now, the first thing the coroutine does is to put itself onto a thread pool. Like:
  `co_await item->scheduler.schedule();`
Therefore, the caller gets control back right away. I do **not** want to wait for it to finish. Question is... what do I do with the task<void> object? I cannot destroy it, that destroys the coroutine as well. I do not want to wait for it. I cannot not put it onto the heap, that will create a memory leak. 

I've seen some reference counting for this problem in other libraries, but what should I do in this library?

Greetings, Jørn

**Comment by jbaldwin** [comment]
Hi, does this coroutine return something other than void?  If it is returning void I'd recommend looking at https://github.com/jbaldwin/libcoro#task_container This container is meant for arbitrary lifetime tasks that need to auto delete upon completion.
