### ISSUE TITLE
null-pointer access and crash in coro::mutex::unlock() during stress test

### ISSUE THREAD

**Issue by Ankkatalo** [jbaldwin/libcoro#107]
Crashes in line 
`to_resume->m_awaiting_coroutine.resume();`
because m_awaiting_coroutine is nullptr. But the operation is not created with a nullptr.

Possible cause: The member m_awaiting_coroutine is set too late in the function
`coro::mutex::lock_operation::await_suspend()`
It is set after adding the operation to the list, which seems wrong to me.

Greetings, Jørn

**Comment by jbaldwin** [comment]
this is happening in the existing tests? or did you add some new ones?

**Comment by jbaldwin** [comment]
pushed a patch fix so hopefully this fixes it.  Nice find! thanks for reporting

**Comment by Ankkatalo** [comment]
My stress test does no longer crash and the fix makes sense to me, I consider this solved.
