### ISSUE TITLE
coco::detail::promise<void>::return_void(): Misplaced rethrow

### ISSUE THREAD

**Issue by Ankkatalo** [jbaldwin/libcoro#109]
Greetings.

I'm looking at task.hpp here.

You're using coro::detail::promise<void>::return_void() to rethrow the exception after the end of the coroutine. That part I understand.

But according to the spec, promise::return_void() is also called automatically during co_return. From the coroutine itself. Where a rethrow makes no sense.

This is a strange double use of the function, and I think it's just a bug. Or I don't get it, which is always a possibility.
In the case of promise-of-not-void you also use return_value() function for two purposes, but that works since they are distinct by parameter overload.

Best Regards, Jørn

**Comment by jbaldwin** [comment]
Been out and about, I'll take a look tomorrow if I have some time.

**Comment by jbaldwin** [comment]
This does indeed look like a bug, the `return_value(v)` is overloaded here one with an arg and one without where `return_value() -> T` is used in the task itself later, not by the compiler.  I've incorrectly used this function twice on the `void` one in task.hpp around lines 208 and 230.

Probably renaming the libraries `return_void()` and `return_value() -> T` used within `task` to something else would remedy this?

**Comment by jbaldwin** [comment]
@Ankkatalo I've posted a PR https://github.com/jbaldwin/libcoro/pull/110 if you have time please take a look over it.

**Comment by Ankkatalo** [comment]
looks good to me.

**Comment by jbaldwin** [comment]
Merged and tagged as `v0.3`
