### ISSUE TITLE
A performance comparison

### ISSUE THREAD

**Issue by beef9999** [jbaldwin/libcoro#119]
Would you like to provide some tcp echo server code so I can add a comparison into our [project](https://github.com/alibaba/PhotonLibOS#21-tcp).

**Comment by jbaldwin** [comment]
There are two benchmark tests:

https://github.com/jbaldwin/libcoro/blob/main/test/bench.cpp#L348 for using a thread pool to handle connections and https://github.com/jbaldwin/libcoro/blob/main/test/bench.cpp#L553 for handling requests inline in the event loop.  Is this what you are looking for?

**Comment by jbaldwin** [comment]
closing since this hasn't had any movement since july
