### ISSUE TITLE
coro::task<T> expects T to be default-constructible even if the default constructor is never used

### ISSUE THREAD

**Issue by LordTermor** [jbaldwin/libcoro#163]
I don't know if it's intended and couldn't find any discussion regarding this.

```
struct A {
    A(int bar) {} //no default constructor
};

coro::task<A> foo() {
    co_return A(2);
} // doesn't compile
```

Seems the `promise` type needs default-constructed `m_return_value`.
https://github.com/jbaldwin/libcoro/blob/6a631de928bcdecaadfc72a77528c4a7dbceec18/inc/coro/task.hpp#L120

**Comment by jbaldwin** [comment]
Hey @LordTermor, thanks for reporting this problem, this is indeed a bug.  I've pushed a PR which addresses the issue and adds a test to verify that the code you submitted compiles.  Can you please take a look and try it out? Thanks.

**Comment by LordTermor** [comment]
Hey. Thank you! Works flawlessly on my side.
