### ISSUE TITLE
Explore using libuv for cross platform io support

### ISSUE THREAD

**Issue by jbaldwin** [jbaldwin/libcoro#248]
The use of linux epoll works great for linux, but its a fairly significant amount of functionality that users of other platforms cannot use since `coro::io_scheduler` is linux specific.

1. Try and see how difficult it would be to retrofit the io functionality with libuv
2. If reasonable run benchmarks and see if there is any major performance penalty.
3. How difficult is it to build with libuv as a dependency? Should it be compiled directly in or is it possible on all platforms to install as a shared library and linked to?

**Comment by jbaldwin** [comment]
I think for now we'll keep dependencies lean and not go down this path at this time.

**Comment by jmpews** [comment]
hi, is there any updated? 😊

**Comment by jbaldwin** [comment]
@jmpews hi, I haven't considered doing any work on this for a while, my main reason in doing so was to avoid introducing another dependency to the project.

But I still think it would be an interesting thing to try to see how difficult it would be and if the performance on Linux would be as close as the current Linux epoll implementation.

Would you have any interest in taking a try at it?
