### ISSUE TITLE
Lost values when combined with std::views::take

### ISSUE THREAD

**Issue by mikucionisaau** [jbaldwin/libcoro#261]
Not sure if that's a bug or a feature.

Consider the following program (using `libcoro` from `v0.11.1` and `main`):
```cpp
#include <coro/coro.hpp>
#include <ranges>
#include <iostream>

coro::generator<size_t> Naturals() {
    auto n = 0z;
    while (true) {
        ++n;
        co_yield n;
    }
}

int main() {
    auto n = Naturals();
    for (auto i : n | std::views::take(3))
        std::cout << i << ' ';
    std::cout << '\n';
    for (auto i : n | std::views::take(3))
        std::cout << i << ' ';
    std::cout << '\n';
}
```

It prints the following:
```
1 2 3 
5 6 7 
```

I expect:
```
1 2 3 
4 5 6 
```
Note: `4` is missing.

If I try `std::generator` in GCC-14, then [it fails to find `operator|`](https://godbolt.org/z/687Yrhzer) -- such composition is not even accepted.

Any ideas?

**Comment by mikucionisaau** [comment]
I replaced `coro::generator` with `std::views::iota` and it seems that `operator|` consumes the range by copy:
```cpp
int main() {
    auto n = std::views::iota(1);
    for (auto i : n | std::views::take(3))
        std::cout << i << ' ';  // 1 2 3
    std::cout << '\n';
    for (auto i : n | std::views::take(3))
        std::cout << i << ' ';  // 1 2 3
    std::cout << '\n';
}
```

Meanwhile `std::generator` and `coro::generator` do not allow copies and hence `std::generator& | std::views::take` fails, but it works on rvalue-references.

So maybe `coro::generator& | std::views::take` should not be allowed as it gives unexpected results like in the original report -- unsafe. Albeit it would still be nice to bind by lvalue reference and then issue a friendly error message with `static_assert` (not just "failed to find operator|" which appears as incomplete functionality).

**Comment by mikucionisaau** [comment]
Alternatively, `std::views::take` could be fixed not to request more values than necessary. 
Currently it requests one too many values and thus puts the generator into a unexpected state.

**Comment by jbaldwin** [comment]
Hey @mikucionisaau been a busy week, I'll try and take a look at this as soon as I can.  Thanks for reporting the issue.

**Comment by mikucionisaau** [comment]
Here is my replacement for `std::views::take` using `coro::generator`:
```cpp
namespace coro {
    template <std::ranges::input_range Range, typename Item = std::iter_value_t<std::ranges::iterator_t<Range>>>
    coro::generator<Item> take(Range&& range, size_t count) {
        auto it = std::ranges::begin(range);
        auto e = std::ranges::end(range);
        if (count-->0 && it != e)
            co_yield *it;
        while (count-->0 && ++it != e)
            co_yield *it;
    }

    struct take_adapter { size_t count; };
    take_adapter take(size_t count) { return take_adapter{count}; }

    template <std::ranges::input_range Range, typename Item = std::iter_value_t<std::ranges::iterator_t<Range>>>
    coro::generator<Item> operator|(Range&& range, take_adapter& adapter) {
        return take(std::forward<Range>(range), adapter.count);
    }
    template <std::ranges::input_range Range, typename Item = std::iter_value_t<std::ranges::iterator_t<Range>>>
    coro::generator<Item> operator|(Range&& range, take_adapter&& adapter) {
        return take(std::forward<Range>(range), adapter.count);
    }}
```

It's a bit of overkill to use coroutine, but you can see where `std::views::take` can take too much. 
GCC-13 `std::views::take` uses `counted_iterator`, which has overly simple increment operators at `stl_iterator.h:2418`: it increments the iterator despite the counter reaching zero. Counter reaching 0 means "one passed the range" (just like `std::end`), but in case of generators it means fetching one more value which is then discarded:

```cpp
      constexpr counted_iterator&
      operator++()
      {
	__glibcxx_assert(_M_length > 0);
	++_M_current;
	--_M_length;
	return *this;
      }
```
Fix would require adding an `if` branching statement potentially hindering the performance :-(

**Comment by jbaldwin** [comment]
Apologies on the very slow response, life has been busy, do you have a possible PR you could push that fixes this?

**Comment by mikucionisaau** [comment]
Found one predicate which distinguishes the generators:
```cpp
auto sn = StdNaturals();
static_assert(std::ranges::view<decltype(sn)>, "is not a view"); // passes
auto cn = CoroNaturals();
static_assert(std::ranges::view<decltype(cn)>, "is not a view"); // fails
```
then `std::ranges::view` is defined as:
```cpp
template<class T>
concept view = ranges::range<T> && std::movable<T> && ranges::enable_view<T>;
```
`range` and `movable` are satisfied by both, meanwhile `enable_view` is present only in `std::generator`.

`enable_view`:
```cpp
template<typename _Tp>
inline constexpr bool enable_view = derived_from<_Tp, view_base>
      || __detail::__is_derived_from_view_interface<_Tp>;
```

Basically, the `coro::generator` needs to inherit from `std:ranges::view_base` to be treated just like `std::generator` (then `std::views::take` does not wrap it into copyable `ref_view` with a pointer). 

Here is solution patch:
```patch
diff --git a/include/coro/generator.hpp b/include/coro/generator.hpp
index 5fba1d0..a15305a 100644
--- a/include/coro/generator.hpp
+++ b/include/coro/generator.hpp
@@ -118,7 +118,7 @@ private:
 } // namespace detail
 
 template<typename T>
-class generator
+class generator : public std::ranges::view_base
 {
 public:
     using promise_type = detail::generator_promise<T>;
```

I cannot really add a test for this "feature", because it requires that the compiler fails on it. Very weird.

**Comment by mikucionisaau** [comment]
Found a talk explaining design decisions behind exactly this issue:
[take(5): Using the C++ Iterator Model to Take Elements from an Input Stream - Barry Revzin - CppNow](https://youtu.be/dvi0cl8ccNQ(
