### ISSUE TITLE
libcoro fails to build on opensuse

### ISSUE THREAD

**Issue by niansa** [jbaldwin/libcoro#88]
My system is OpenSuse Tumbleweed.

Here is the build log:
https://gist.github.com/niansa/2b684cab7016001fdbe2d2c1c0cf3c7d

**Comment by jbaldwin** [comment]
Thanks for the report. Should be pretty easy to add opensuse CI check, I'll get a PR going in a bit.

Looks like it probably needs an adjustment in the cmakelists.txt in some manner due to linker issues.

**Comment by jbaldwin** [comment]
Hmm interestingly this doesn't seem to happen on a debug build, but I have managed to replicate it via the added CI.
