### ISSUE TITLE
Can't schedule io_scheduler in generator function

### ISSUE THREAD

**Issue by niansa** [jbaldwin/libcoro#89]
That'd be extremely useful!

**Comment by jbaldwin** [comment]
Could you add an example here of exactly what you are looking for? I think I understand but always good to clarify with a code snippet!

**Comment by niansa** [comment]
Of course :smile: 
https://gist.github.com/niansa/1cd2b593471a377bf7b3a54c10039606

**Comment by jbaldwin** [comment]
Seems like you are looking for something like this?
* https://github.com/lewissbaker/cppcoro#async_generatort

I haven't added support to the `coro::generator<T>` to support anything other than basic `co_yield` yet, so its probably a pretty good uplift to get this implemented.  Give me some time to think on this one, but based on what you're doing this is a fairly similar example of the server handling a recv and then send back: https://github.com/jbaldwin/scopuli/blob/327664f3fc23b3147fce5dfa885c1dd55007f9f0/src/scopuli.cpp#L108

Can you compose your `send` function in a similar way as this example or similarly?

**Comment by niansa** [comment]
thanks a lot!
