### ISSUE TITLE
I need an example for using TCP client with TLS

### ISSUE THREAD

**Issue by niansa** [jbaldwin/libcoro#90]
Hey, from what I have understood I need to give the TCP client class a pointer to a TLS context? But where does that pointer come from? Should I allocate it using the `new` keyword?
Also, what are these files I need to pass to the TLS context constructor?

**Comment by jbaldwin** [comment]
Thats correct, to enable TLS you'll need a context, which creates the openssl structures to be used by the `io_scheduler`.  

If you look into `test_tcp_server.cpp` line 85 there is an example client/server using TLS.  Probably worth making it first class in the README.

**Comment by niansa** [comment]
Yep sounds good thanks.

**Comment by niansa** [comment]
One more question, where do I get these two files I need to provide from?

**Comment by jbaldwin** [comment]
You can generate keys and certs via the `openssl` cli tool.  The `test/main.cpp` file within `libcoro` has an example on a basic key/cert pair to run the tests.

**Comment by niansa** [comment]
Why is that required on the client to have a private certificate?

**Comment by niansa** [comment]
Nevermind me! I can just pass nothing to the constructor.

**Comment by jbaldwin** [comment]
It's not required on the client, if you look at the `coro::net::ssl_context` class it does have a default constructor you can use that won't import any keys or certs.  However, if you don't provide a cert/key pair the server you are connecting to won't be able to verify the client's identity, which may or may not be a problem for your use case.
