### ISSUE TITLE
coro::event LIFO/FIFO policy

### ISSUE THREAD

**Issue by jbaldwin** [jbaldwin/libcoro#97]
Add a `coro::event::set` param with defaults to LIFO (current) but if set to FIFO then the linked list is reversed before it is resumed.

**Comment by jbaldwin** [comment]
@niansa if you want to take a look at this PR, I think its what you were looking for, I came up with a way that doesn't explode the size of the class but only incurs a slight runtime performance cost to reverse the order of the waiters.

**Comment by niansa** [comment]
Perfect, yep! Thanks a lot!!!
