### ISSUE TITLE
detaching coroutine from current one?

### ISSUE THREAD

**Issue by niansa** [jbaldwin/libcoro#98]
Hey, how would I detatch a coroutine from the current one?

I know that in libasync it's done like this:

    async::detach(coroutine());

But no such exists in libcoro.

**Comment by niansa** [comment]
I figured out `coro::when_all()`.

But how do I configure it so when one coroutine end all others are ended too?

**Comment by jbaldwin** [comment]
I haven't written a `coro::when_any` yet, if that is what you are looking for?  Its pretty hard to stop a users code.. and from my understanding 'detach' generally just removes the parent's ability to join the thread of execution.  `std::jthread` (new in c++20) does allow stopping via a `std::stop_token` but it still requires the user's code to check it and return.

I think if you just want the coroutines to all run to completion you should use `coro::thread_pool` or `coro::io_scheduler`, these will both effectively detach the scheduled coroutines from your point of scheduling and then they will all run until they complete independently of each other.  `coro::io_scheduler` also has a policy to run coroutines inline on the i/o thread if you do not want to jump threads during execution.

**Comment by niansa** [comment]
Sounds great! Yep `coro::when_any` is what I need. I think for now I will just set a bool and make my coroutines return by checking that bool

**Comment by jbaldwin** [comment]
I suppose a minimal implementation could wrap the user's coroutine with a check before starting to see if the previous one had completed -- this would work well for singly threaded use cases but would break down in a multi-threaded use case since its possible to start many before one finishes.

A bool check works great if your running on a single thread.

**Comment by niansa** [comment]
Yep, my game is single-threaded :+1:

**Comment by niansa** [comment]
Follow-up question: I want to detach my entities loops from the main loop. How would I do that?

**Comment by niansa** [comment]
Nwevermind, it's io_scheduler::scheduler!
